# Generated by Django 4.1.4 on 2023-03-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_livesession_news"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="CurrentNews",
        ),
    ]
