# Generated by Django 4.1.4 on 2023-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_news_currentnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentnews",
            name="image",
            field=models.ImageField(
                default="avatar.svg", null=True, upload_to="NewImages/"
            ),
        ),
    ]
