# Generated by Django 4.1.4 on 2023-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_livesession_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livesession",
            name="youtubeLink",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
