# Generated by Django 4.1.4 on 2023-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_livesession_youtubelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livesession",
            name="youtubeLink",
            field=models.TextField(blank=True),
        ),
    ]
